[card.sangan]
id = 99999999
setnumber = "${_SETN|001}"
ot = "custom"
set = "sangan-set"
attribute = "dark"
race = "fiend"
type = "monster effect"
level = 3
atk = 1000
def = 600

[card.witch]
id = 99999998
setnumber = "${_SETN|002}"
ot = "custom"
set = "sangan-set"
attribute = "dark"
race = "spellcaster"
type = "monster effect"
level = 4
atk = 1200
def = 800

[card.lastwill]
id = 99999997
setnumber = "${_SETN|003}"
ot = "custom"
set = "sangan-set"
type = "spell normal"

