[macro]
_SETN = "WBF"

[card.witch]
id = 99999998
setnumber = "${_SETN|001}"
ot = "custom"
set = "sangan-set"
attribute = "dark"
race = "spellcaster"
type = "monster effect"
level = 4
atk = 1200
def = 800
